# ===============================================
# CONFIGURACIÃ“N PRINCIPAL
# ===============================================
server:
  port: 9090

spring:
  profiles:
    active: dev

  security:
    filter:
      dispatcher-types: REQUEST

  application:
    name: nebula-backend-app