spring:
  profiles:
    active: dev  # Perfil por defecto

server:
  port: 9090

# Configuración común para TODOS los entornos
logging:
  level:
    com.example.nebulaBackendApp: INFO

jwt:
  secret-key: "clave-secreta-para-desarrollo-local-123456"
  expiration-time: 86400000