spring:
  profiles:
    active: dev

  datasource:
    # ðŸš¨ CAMBIO CLAVE 1: Usamos el driver de MySQL en lugar de PostgreSQL
    driver-class-name: com.mysql.cj.jdbc.Driver

    # ðŸš¨ CAMBIO CLAVE 2: Usamos el prefijo URL de MySQL.
    # El valor predeterminado asume que MySQL estÃ¡ en localhost:3306 y la base de datos se llama 'mydatabase'.
    url: ${DB_URL:jdbc:mysql://localhost:3306/nebula_dbApp?serverTimezone=UTC}

    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mypassword}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9090